# Generated by Django 5.0.6 on 2026-07-25 21:52

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    for profile in StudentProfile.objects.all():
        if not profile.public_slug:
            base = slugify(profile.user.name) or "learner"
            profile.public_slug = f"{base}-{uuid.uuid4().hex[:3]}"
            profile.save(update_fields=["public_slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mentor_recommendation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_slugs, noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
