# Generated by Django 5.0.6 on 2026-07-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
