# Generated by Django 5.0.6 on 2026-07-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0002_task_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='learning_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_output_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image / Photo'), ('github_url', 'GitHub URL'), ('live_url', 'Live URL'), ('code', 'Code')], default='text', max_length=20),
        ),
    ]
