# Generated by Django 5.0.6 on 2026-07-25 13:20

import certifications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
        ('mentors', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('graduate', 'Graduate')], default='beginner', max_length=20)),
                ('mentor_notes', models.TextField(blank=True)),
                ('cert_unique_id', models.CharField(default=certifications.models.gen_cert_code, max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.mentorprofile')),
                ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chains.taskchain')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
