# Generated by Django 5.0.6 on 2026-07-25 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submission_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('github_url', 'GitHub URL'), ('live_url', 'Live URL'), ('code', 'Code')], default='text', max_length=20)),
                ('text_content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('code_content', models.TextField(blank=True)),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('feedback_tags', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='chains.task')),
            ],
        ),
    ]
