# Generated by Django 5.0.6 on 2026-07-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='submissions/files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image / Photo'), ('github_url', 'GitHub URL'), ('live_url', 'Live URL'), ('code', 'Code')], default='text', max_length=20),
        ),
    ]
