# Generated by Django 5.0.6 on 2026-07-25 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_url', models.URLField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('teaching_levels', models.JSONField(default=dict)),
                ('session_rate', models.PositiveIntegerField(default=300)),
                ('bio', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_checks', models.JSONField(default=dict)),
                ('rating', models.FloatField(default=0.0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='mentors.mentorprofile')),
            ],
        ),
    ]
